### ISSUE TITLE
Getting Logged out of my Google Account

### ISSUE THREAD

**Issue by ArnyminerZ** [leikoilja/glocaltokens#8]
**Describe the bug**
When I use the script, when it's executed I get logged out of the Google Account of my Android phone.

**To Reproduce**
I have developed an [script](https://github.com/ArnyminerZ/HomeAssistant-GoogleHome) for Home Assistant that loads the alarms from my Lenovo Smart Clock, and loads them. When I use the script with the following sensor configuration:
```
  - platform: command_line
    command: /home/homeassistant/clock.sh
    name: alarms
    scan_interval: 30
    json_attributes:
      - alarm
      - timer
    value_template: "{{ value_json.alarm[0] }}"
```
when it gets executed, my Google Account at my Android Phone gets bugged, and asks me to log in again, blocking the use of any Google App at my device until I log in again.

**Expected behavior**
I should not get logged out.

**Server:**
 - OS: Raspbian OS
 - Version: `Linux emonpi 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux`
 - Platform: Home Assistant (`2021.2.0`)
 - Python Version: `3.8.7`

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android
 - Version: 11 (`RQ1A.210205.004`)

**Additional context**
I'm using an app password instead of my Google's Account password.
